### ISSUE TITLE
Give ResetWindow same UI look

### ISSUE THREAD

**Issue by KnapSac** [KnapSac/TrafficJam#102]
The ResetWindow I just added needs to have the same look as the rest of the UI. It also needs our logo as the icon.

**Comment by Yvanovski** [comment]
ResetWindow now has the same look and icon, effect of buttons however has not been restored, old code is in comments. The user can simply press the X instead of a cancel button, this makes the UI cleaner.

**Comment by KnapSac** [comment]
The OK and Cancel button are missing, I would like to have both, but we definitely need a Cancel button. From the users standpoint, it isn't very user friendly if they want to cancel this action right now.
