### ISSUE TITLE
sudden stackoverflow error

### ISSUE THREAD

**Issue by ikbenwasmachine** [KnapSac/TrafficJam#122]
tool list en flags toegevoegd aan road, plotseling stackoverflowexception wanneer ik de map laad
![sudden stackoverflowerror](https://user-images.githubusercontent.com/55793121/71739388-8f568300-2e59-11ea-935b-1c01df2e58f8.png)

**Comment by KnapSac** [comment]
In which class are you getting this error?

**Comment by KnapSac** [comment]
You should also update your branch from develop, because it looks like your behind by about 230 commits, so this issue could already be resolved in develop.
