### ISSUE TITLE
Clean up UI

### ISSUE THREAD

**Issue by Yvanovski** [KnapSac/TrafficJam#155]
I will fix most of this, we just need the throughputMeterPanel to work.

- [x] The tools panel is missing buttons and does not look neat anymore

- [x] The traffic flow panel trackbars are not centered anymore

- [x] The throughput meter panel needs to be fixed all together

- [x] The menu panels are less wide than the button row
 
- [x] When the user clicks on a tile which is not an EntryPoint, all EntryPoint subpanels should be deselected

- [x] optional: prevent menu flicker by creating public variable menuOpened

**Comment by KnapSac** [comment]
- [ ] When the user clicks on a tile which is not an EntryPoint, all EntryPoint subpanels should be deselected
