### ISSUE TITLE
Tools basis (met manouk)

### ISSUE THREAD

**Issue by ikbenwasmachine** [KnapSac/TrafficJam#20]
basis voor de tools maken, basis eigenschappen zoals mogelijke tools en welke aanstaat

**Comment by KnapSac** [comment]
Ik zie dat je deze issue als 'Done' had gemarkeerd, ik weet niet of je dat lokaal af hebt, of dat het een foutje was, maar in het geval dat je het lokaal klaar hebt, push het dan naar je branch, maak vanaf je branch een pull request naar develop met in de beschrijving 'Closes #20 ', en zorg dat de pull request gemerged wordt. Op dat moment sluit deze issue automatisch in wordt hij ook automatisch in de 'Done' kolom geplaatst. Op die manier weten we dat de code voor een issue die als 'Done' gemarkeerd staat ook al op de 'develop' branch staat.

**Comment by KnapSac** [comment]
Voor de Code Review zou ik graag zien dat het mogelijk is om tools te plaatsen/verwijderen, en er moet natuurlijk bijgehouden worden welke Tool aanstaat.

**Comment by ikbenwasmachine** [comment]
> Voor de Code Review zou ik graag zien dat het mogelijk is om tools te plaatsen/verwijderen, en er moet natuurlijk bijgehouden worden welke Tool aanstaat.

vorige woensdag was afgesproken dat ik en manouk er voor zouden zorgen dat je tools kon selecteren en dat dit goed werkte (je kan makkelijk tools toevoegen). Dit was gedaan dus als done gemarkeerd maar als je wil dat we er ook plaatjes voor zoeken en op de map toevoegen zullen we kijken wat we kunnen doen!

**Comment by KnapSac** [comment]
Dat zou voor vrijdag wel mooi zijn, maar is niet helemaal wat ik bedoelde. Het is de bedoeling dat een issue pas geclosed wordt als de code op de develop branch staat, als je dat doet op de manier die ik hier boven aangaf gaat dat automatisch
