### ISSUE TITLE
Update the current tool when the button is clicked in toolsPanel

### ISSUE THREAD

**Issue by Yvanovski** [KnapSac/TrafficJam#45]
I tried this in the function crossRoad_Click in MainWindow

**Comment by KnapSac** [comment]
You should use the MouseClick eventhandler of the Map, when called it should check which button is pressed (left or right), and based on that it should either place or remove a tool. If the current tool isn't placed on the selected tile, the eventhandler should do nothing, but if the tool is placed, it should remove the tool. If the button is left, we should check whether that tool is allowed on that tile, by using the ToolAllowed method on the Road. That method returns a boolean value whether placement is allowed. If placement isn't allowed, we should let the user know. We also need to handle a user placing the same tool twice on the same tile, which isn't possible off course.
