### ISSUE TITLE
Ideas on how the EntryPointsPanel should work

### ISSUE THREAD

**Issue by Yvanovski** [KnapSac/TrafficJam#46]
What should be changeable in this menu, only amount of traffic inflow?
How could the program determine the amount of entry points on a map?

**Comment by KnapSac** [comment]
Right now the entrypoints are hard coded on creating of the Map, so we can access the List in which they are stored. I believe we discussed in one of our earlier meetings what this should do, so you could probably take a look at the notes for our meetings.

**Comment by Yvanovski** [comment]
I can access the list now, but there are no notes on this from our meetings
