### ISSUE TITLE
Create additional situations

### ISSUE THREAD

**Issue by KnapSac** [KnapSac/TrafficJam#52]
Currently we have only one situation, but I would like to have more. It should be pretty easy to add 2 more situations, because we can easily copy the first one. These are the things that need to be done for the situations:

Situation 1:
- [x] Name
- [x] Description

Situation 2:
- [x] Name
- [x] Description
- [x] Road layout
- [x] Preview

Situation 3:
- [x] Name
- [x] Description
- [x] Road layout
- [x] Preview

**Comment by ManoukSirag** [comment]
Situation 1 & 2 might need to be changed, since they're not real places.
Previews can't be made right now since the MainWindow in the developer branch is broken (part of the map is cut of by the edge of the window)

**Comment by KnapSac** [comment]
Actually, as mentioned during the presentation, the situations don't need to be actual places, so I agree situation 1 needs to be changed, but the new situations can be fictitious. Don't worry about the preview, I'll take care of that once the road layouts are done, so just let me know when I can merge your branch into develop, then I'll make the previews.

**Comment by ManoukSirag** [comment]
Branch newmaps can be merged into develop for now. only the previews are left. changed to the situations can be made later if these ones aren't good. 
I kept the first situation the same for now since it's being used as testmap for the simulation
